message(STATUS "Start compile thirdparty dependeny: jemalloc")

ExternalProject_Add(jemalloc
  PREFIX ${DEPENDENCIES_BUILD_DIR}/jemalloc
  SOURCE_DIR ${DEPENDENCIES_DIR}/jemalloc
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CONFIGURE_COMMAND git clean -df COMMAND ./autogen.sh --prefix=${DEPENDENCIES_INSTALL_DIR}
  BUILD_COMMAND make clean COMMAND make
  BUILD_IN_SOURCE 1
  INSTALL_COMMAND make install
  TEST_COMMAND ""
)

set(JEMALLOC_FOUND TRUE)
set(JEMALLOC_INCLUDE_DIRS ${DEPENDENCIES_INSTALL_DIR}/include)
set(JEMALLOC_LIBRARY_DIRS ${DEPENDENCIES_INSTALL_DIR}/lib})
set(JEMALLOC_LIBRARIES ${DEPENDENCIES_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}jemalloc${CMAKE_SHARED_LIBRARY_SUFFIX})