message(STATUS "Start compile thirdparty dependeny: tmxparser")

ExternalProject_Add(tmxparser
  PREFIX ${DEPENDENCIES_BUILD_DIR}/tmxparser
  SOURCE_DIR ${DEPENDENCIES_DIR}/tmxparser
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
             -DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}
             -DZLIB_LIBRARIES=${ZLIB_LIBRARIES}
             -DTINYXML_LIBRARIES=${TINYXML_LIBRARIES}
  TEST_COMMAND ""
)

set(TMXPARSER_FOUND TRUE)
set(TMXPARSER_INCLUDE_DIRS ${DEPENDENCIES_INSTALL_DIR}/include)
set(TMXPARSER_LIBRARY_DIRS ${DEPENDENCIES_INSTALL_DIR}/lib})
set(TMXPARSER_LIBRARIES ${DEPENDENCIES_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}tmxparser${CMAKE_SHARED_LIBRARY_SUFFIX})