message(STATUS "Start compile thirdparty dependeny: aprutil")

ExternalProject_Add(aprutil
  PREFIX ${DEPENDENCIES_BUILD_DIR}/apr-util
  SOURCE_DIR ${DEPENDENCIES_DIR}/apr-util
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CONFIGURE_COMMAND ./buildconf COMMAND ./configure --prefix=${DEPENDENCIES_INSTALL_DIR} -with-apr=${DEPENDENCIES_INSTALL_DIR}/
  BUILD_COMMAND make clean COMMAND make
  BUILD_IN_SOURCE 1
  INSTALL_COMMAND make install
  TEST_COMMAND ""
)

set(APRUTIL_FOUND TRUE)
set(APRUTIL_INCLUDE_DIRS ${DEPENDENCIES_INSTALL_DIR}/include)
set(APRUTIL_LIBRARY_DIRS ${DEPENDENCIES_INSTALL_DIR}/lib})
set(APRUTIL_LIBRARIES ${DEPENDENCIES_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}aprutl${CMAKE_SHARED_LIBRARY_SUFFIX})