message(STATUS "Start compile thirdparty dependeny: tinyxml")

ExternalProject_Add(tinyxml
  PREFIX ${DEPENDENCIES_BUILD_DIR}/tinyxml
  SOURCE_DIR ${DEPENDENCIES_DIR}/tinyxml
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
             -DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}
  TEST_COMMAND ""
)

set(TINYXML_FOUND TRUE)
set(TINYXML_INCLUDE_DIRS ${DEPENDENCIES_INSTALL_DIR}/include)
set(TINYXML_LIBRARY_DIRS ${DEPENDENCIES_INSTALL_DIR}/lib})
set(TINYXML_LIBRARIES ${DEPENDENCIES_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}tinyxml${CMAKE_SHARED_LIBRARY_SUFFIX})