message(STATUS "Start compile thirdparty dependeny: g3dlite")

ExternalProject_Add(g3dlite
  PREFIX ${DEPENDENCIES_BUILD_DIR}/g3dlite
  SOURCE_DIR ${DEPENDENCIES_DIR}/g3dlite
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
             -DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}
  TEST_COMMAND ""
)

set(G3DLITE_FOUND TRUE)
set(G3DLITE_INCLUDE_DIRS ${DEPENDENCIES_INSTALL_DIR}/include)
set(G3DLITE_LIBRARY_DIRS ${DEPENDENCIES_INSTALL_DIR}/lib})
set(G3DLITE_LIBRARIES ${DEPENDENCIES_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g3dlite${CMAKE_SHARED_LIBRARY_SUFFIX})