message(STATUS "Start compile thirdparty dependeny: sigar")

ExternalProject_Add(sigar
  PREFIX ${DEPENDENCIES_BUILD_DIR}/sigar
  SOURCE_DIR ${DEPENDENCIES_DIR}/sigar
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
             -DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}
  TEST_COMMAND ""
)

set(SIGAR_FOUND TRUE)
set(SIGAR_INCLUDE_DIRS ${DEPENDENCIES_INSTALL_DIR}/include)
set(SIGAR_LIBRARY_DIRS ${DEPENDENCIES_INSTALL_DIR}/lib})
set(SIGAR_LIBRARIES ${DEPENDENCIES_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}sigar${CMAKE_SHARED_LIBRARY_SUFFIX})