message(STATUS "Start compile thirdparty dependeny: hiredis")

ExternalProject_Add(hiredis
  PREFIX ${DEPENDENCIES_BUILD_DIR}/hiredis
  SOURCE_DIR ${DEPENDENCIES_DIR}/hiredis
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
             -DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}
             -DENABLE_SSL=ON
  TEST_COMMAND ""
)

set(HIREDIS_FOUND TRUE)
set(HIREDIS_INCLUDE_DIRS ${DEPENDENCIES_INSTALL_DIR}/include)
set(HIREDIS_LIBRARY_DIRS ${DEPENDENCIES_INSTALL_DIR}/lib})
set(HIREDIS_LIBRARIES ${DEPENDENCIES_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}hiredis_ssl${CMAKE_SHARED_LIBRARY_SUFFIX})