message(STATUS "Start compile thirdparty dependeny: Zlib")

ExternalProject_Add(zlib
  PREFIX ${DEPENDENCIES_BUILD_DIR}/zlib
  SOURCE_DIR ${DEPENDENCIES_DIR}/zlib
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
             -DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}
  TEST_COMMAND ""
)

set(ZLIB_FOUND TRUE)
set(ZLIB_INCLUDE_DIRS ${DEPENDENCIES_INSTALL_DIR}/include)
set(ZLIB_LIBRARY_DIRS ${DEPENDENCIES_INSTALL_DIR}/lib})
set(ZLIB_LIBRARIES ${DEPENDENCIES_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}z${CMAKE_SHARED_LIBRARY_SUFFIX})