message(STATUS "Start compile thirdparty dependeny: fmt")

ExternalProject_Add(fmt
  PREFIX ${DEPENDENCIES_BUILD_DIR}/fmt
  SOURCE_DIR ${DEPENDENCIES_DIR}/fmt
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
             -DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}
             -DBUILD_SHARED_LIBS=TRUE
  TEST_COMMAND ""
)

set(FMT_FOUND TRUE)
set(FMT_INCLUDE_DIRS ${DEPENDENCIES_INSTALL_DIR}/include)
set(FMT_LIBRARY_DIRS ${DEPENDENCIES_INSTALL_DIR}/lib})
set(FMT_LIBRARIES ${DEPENDENCIES_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}fmtd${CMAKE_SHARED_LIBRARY_SUFFIX})